### PR TITLE
Bump the node engine requirement to v14 or later.

### PR DESCRIPTION
**Pull request by sedwards2009**
The JS code uses ES6 `import` but this only works out of the box on node v14 or later.

### CODE REVIEW

**Comment by sedwards2009** [comment]
BTW, this little program is going to help a lot hunting down some memory leaks. thanks.

**Comment by dnachev** [comment]
Thanks @sedwards2009 . I've tested locally with node `12.18` and it seems to be working as expected, so I've downgraded it. If it's working for you, I will merge it in.

**Comment by dnachev** [comment]
I've merged the change. If it doesn't work for you, let me know I will try to look into it.

**Comment by sedwards2009** [comment]
thanks.

**Pull request merged**
